src/Entity/Quack.php
<?php

namespace App\Entity;

use App\Repository\QuackRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: QuackRepository::class)]
class Quack
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $content = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $created_at = null;

    #[ORM\ManyToOne(inversedBy: 'quacks')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\Column(nullable: true)]
    private ?int $parent_id = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getParentId(): ?int
    {
        return $this->parent_id;
    }

    public function setParentId(?int $parent_id): self
    {
        $this->parent_id = $parent_id;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['duckname'], message: 'There is already an account with this duckname')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $duckname = null;

    #[ORM\Column]
    private array $roles = [];

    #[ORM\Column(length:64, nullable: true)]
    private ?string $firstName = null;

    #[ORM\Column(length:64, nullable: true)]
    private ?string $lastName = null;

    #[Assert\NotBlank]
    #[ORM\Column(length:180, unique: true, nullable: true)]
    private ?string $email = null;

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Quack::class, orphanRemoval: true)]
    private Collection $quacks;

    public function __construct()
    {
        $this->quacks = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDuckname(): ?string
    {
        return $this->duckname;
    }

    public function setDuckname(string $duckname): self
    {
        $this->duckname = $duckname;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return strtoupper($this->lastName);
    }

    public function getFullName(): ?string
    {
        return $this->getFirstName() . ' ' . $this->getLastName();
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->duckname;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection<int, Quack>
     */
    public function getQuacks(): Collection
    {
        return $this->quacks;
    }

    public function addQuack(Quack $quack): self
    {
        if (!$this->quacks->contains($quack)) {
            $this->quacks->add($quack);
            $quack->setUser($this);
        }

        return $this;
    }

    public function removeQuack(Quack $quack): self
    {
        if ($this->quacks->removeElement($quack)) {
            // set the owning side to null (unless already changed)
            if ($quack->getUser() === $this) {
                $quack->setUser(null);
            }
        }

        return $this;
    }
}

src/Form/QuackType.php
<?php

namespace App\Form;

use App\Entity\Quack;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class QuackType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('content', TextareaType::class, ['required' => true, 'label' => false])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Quack::class,
        ]);
    }
}

src/Controller/QuackController.php
<?php

namespace App\Controller;

use App\Entity\Quack;
use App\Form\QuackType;
use App\Repository\QuackRepository;
use App\Services\QuackService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Route('/quack')]
class QuackController extends AbstractController
{
    #[Route('/', name: 'app_quack_index', methods: ['GET'])]
    public function index(QuackRepository $quackRepository): Response
    {
        return $this->render('quack/index.html.twig', [
            'quacks' => $quackRepository->findAll(),
        ]);
    }

    #[IsGranted('ROLE_USER')]
    #[Route('/new', name: 'app_quack_new', methods: ['GET', 'POST'])]
    public function new(Request $request, QuackService $quackService): Response
    {   
        # Formulaire d'ajout d'un nouveau Quack
        $quack = new Quack();
        $form = $this->createForm(QuackType::class, $quack);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            
            $quackService->handleQuackForm($quack);
            return $this->redirectToRoute('app_home', [], Response::HTTP_SEE_OTHER);
        }

        # Afficher le template
        return $this->render('quack/new.html.twig', [
            'quack' => $quack,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_quack_show', methods: ['GET', 'POST'])]
    public function show(Quack $quack, Request $request, QuackService $quackService, QuackRepository $quackRepository): Response
    {
        # Le quack est récupéré automatiquement grâce au ParamConverter
        # pas besoin de $quack = $quackRepository->find($id);
        
        # Récupérer les enfants de ce Quack
        $quacksAnswers = $quackRepository->getQuacksAnswers($quack);
        
        # Préparer le formulaire de réponse à un Quack
        $quackAnswer = new Quack();
        $quackForm = $this->createForm(QuackType::class, $quackAnswer);
        $quackForm->handleRequest($request);

        if ($quackForm->isSubmitted() && $quackForm->isValid()) {

            # Service de gestion du formulaire de Quack, cette fois on passe le parent en second paramètre
            $quackService->handleQuackForm($quackAnswer, $quack); 

            # Rediriger vers la page du quack
            return $this->redirectToRoute('app_quack_show', ['id' => $quack->getId()], Response::HTTP_SEE_OTHER);
        }
        
        # Afficher le template
        return $this->render('quack/show.html.twig', [
            'quack' => $quack,
            'quacksAnswers' => $quacksAnswers,
            'form' => $quackForm->createView(),    
        ]);
    }

    #[IsGranted('ROLE_USER')]
    #[Route('/{id}/edit', name: 'app_quack_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Quack $quack, QuackService $quackService): Response
    {
        # Récupérer l'utilisateur connecté
        $user = $this->getUser();

        # On vérifie que l'utilisateur est bien le propriétaire du Quack à modifier
        if ($quack->getUser() !== $user) {
            throw $this->createAccessDeniedException('You are not the owner of this quack');
        }
        
        # Générer le formulaire d'ajout/modification du Quack
        $form = $this->createForm(QuackType::class, $quack);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            
            $quackService->handleQuackForm($quack);

            return $this->redirectToRoute('app_home', [], Response::HTTP_SEE_OTHER);
        }

        # Afficher le template
        return $this->render('quack/edit.html.twig', [
            'quack' => $quack,
            'form' => $form,
        ]);
    }

    #[IsGranted('ROLE_USER')]
    #[Route('/{id}/delete', name: 'app_quack_delete', methods: ['POST'])]
    public function delete(Request $request, Quack $quack, QuackRepository $quackRepository): Response
    {
        # Validation du token CSRF (voir le template)
        if (! $this->isCsrfTokenValid('delete'.$quack->getId(), $request->request->get('_token'))) {
            throw $this->createAccessDeniedException('You cannot delete this Quack');
        }
        
        # Récupérer l'utilisateur connecté
        $user = $this->getUser();
        
        # On vérifie que l'utilisateur est bien le propriétaire du Quack à supprimer
        if ($quack->getUser() !== $user) {

            # On va vérifier qu'on est peut-être le propriétaire du Quack parent du Quack
            # Dans ce cas, on a le droit de supprimer
            if ( $quack->getParentId() !== null ) {

                # On récupère le parent
                $parent = $quackRepository->find($quack->getParentId());

                # On vérifie que l'on est propriétaire du parent
                if( $parent->getUser() !== $user ) {
                    throw $this->createAccessDeniedException('You are not the owner of this quack');
                }

            } else {
                # Si on n'est pas le propriétaire du quack, ni du quack parent, on ne peut pas supprimer
                throw $this->createAccessDeniedException('You are not the owner of this quack');
            }
        }

        # ⚠️ On supprime d'abord les éventuels Quacks enfants 
        # important de le faire en premier

        # On récupère les Quacks enfants
        $quacksAnswers = $quackRepository->getQuacksAnswers($quack);

        # Et on les supprime un par un
        foreach ($quacksAnswers as $quackAnswer) {
            $quackRepository->remove($quackAnswer, true);
        }
        
        # Enfin, on supprime le Quack original
        $quackRepository->remove($quack, true);

        # Ajouter un message flash de validation
        $this->addFlash(
            'error',
            'Votre quack a été supprimé'
        );

        # On redirige vers la page d'accueil
        return $this->redirectToRoute('app_home', [], Response::HTTP_SEE_OTHER);
    }
}

templates/quack/_delete_form.html.twig
<form 
    method="post" 
    action="{{ path('app_quack_delete', {'id': quackId}) }}" 
    onsubmit="return confirm('Are you sure you want to delete this item?');"
>
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ quackId) }}">
    <button class="text-red-400">Supprimer</button>
</form>

templates/quack/_form.html.twig
<div class="py-6 border-y border-slate-700">
    {{ form_start(form) }}
        {{form_row(form.content, {'attr': {'placeholder': placeholder }} ) }}

        <p class="text-right">
            <button class="py-2 px-4 font-bold rounded-full bg-sky-400">
                {{ button_label|default('Publier') }}
            </button>
        </p>    
    {{ form_end(form) }}
</div>

templates/quack/_quack.html.twig
<li class="py-6 border-b border-slate-700">

  <p class="font-bold">
    {{ quack.user.fullName }}
    <span class="text-sm text-slate-400">@{{quack.user.duckname}}</span>
  </p>

  <p class="text-slate-500">
    Le {{ quack.createdAt|date('d F Y à H\\hi') }}
  </p>

  <p class="my-4 text-base">
    {{quack.content}}
  </p> 

  {% if is_granted('ROLE_USER') %}
    <div class="flex gap-2 text-sm">
      <a class="text-sky-400" href="{{ path('app_quack_show', {'id': quack.id}) }}">Voir</a>

      {% if quack.user == app.user %}
          <a class="text-sky-400" href="{{ path('app_quack_edit', {'id': quack.id}) }}">Modifier</a>
          {% include 'quack/_delete_form.html.twig' with {'quackId': quack.id } %}
      {% endif %}
    </div>
  {% endif %}

</li>

templates/quack/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Quack{% endblock %}

{% block body %}
    <h1>Edit Quack</h1>

    {% include 'quack/_form.html.twig' with {'button_label': 'Mettre à jour'} %}

    <a href="{{ path('app_quack_index') }}">back to list</a>

    {% include 'quack/_delete_form.html.twig' with {'quackId': quack.id } %}
{% endblock %}

templates/quack/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Quack index{% endblock %}

{% block body %}
    <h1>Quack index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Content</th>
                <th>Created_at</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for quack in quacks %}
            <tr>
                <td>{{ quack.id }}</td>
                <td>{{ quack.content }}</td>
                <td>{{ quack.createdAt ? quack.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_quack_show', {'id': quack.id}) }}">show</a>
                    <a href="{{ path('app_quack_edit', {'id': quack.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_quack_new') }}">Create new</a>
{% endblock %}

templates/quack/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Quack{% endblock %}

{% block body %}
    <h1>Create new Quack</h1>

    {% include 'quack/_form.html.twig' with {'placeholder': 'Quoi de neuf ?'} %}

    <a href="{{ path('app_quack_index') }}">back to list</a>
{% endblock %}

templates/quack/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Quack{% endblock %}

{% block body %}
  <h1 class="my-6 text-2xl font-bold">Quack</h1>

  <a class="text-sky-400" href="{{ path('app_home') }}">← Retour aux quacks</a>

  <div class="py-6 border-b border-slate-700">

    <p class="font-bold">
      {{ quack.user.fullName }}
      <span class="text-sm text-slate-400">@{{quack.user.duckname}}</span>
    </p>

    <p class="text-slate-500">
      Le {{ quack.createdAt|date('d F Y à H\\hi') }}
    </p>

    <p class="my-4 text-base">
      {{quack.content}}
    </p> 

    {% if is_granted('ROLE_USER') and quack.user == app.user %}
      <div class="flex gap-2 text-sm">
        <a class="text-sky-400" href="{{ path('app_quack_edit', {'id': quack.id}) }}">Modifier</a>
        {% include 'quack/_delete_form.html.twig' with {'quackId': quack.id } %}
      </div>
    {% endif %}
  </div>

  <h2 class="text-xl my-5">Réponses</h2>
  <ul class="pl-8">
    {% for quackAnswer in quacksAnswers %}
      <li class="py-6 border-b border-slate-700">

        <p class="font-bold">
          {{ quackAnswer.user.fullName }}
          <span class="text-sm text-slate-400">@{{quackAnswer.user.duckname}}</span>
        </p>

        <p class="text-slate-500">
          Le {{ quackAnswer.createdAt|date('d F Y à H\\hi') }}
        </p>

        <p class="my-4 text-base">
          {{quackAnswer.content}}
        </p> 

        {% if is_granted('ROLE_USER') and quackAnswer.user == app.user %}
          <div class="flex gap-2 text-sm">
            <a class="text-sky-400" href="{{ path('app_quack_edit', {'id': quack.id}) }}">Modifier</a>
            {% include 'quack/_delete_form.html.twig' %}
          </div>
        {% elseif is_granted('ROLE_USER') and quack.user == app.user %}
          <div class="flex gap-2 text-sm">
            {% include 'quack/_delete_form.html.twig' with {'quackId': quackAnswer.id } %}
          </div>
        {% endif %}

      </li>
    {% endfor %}
  </ul>

  {% if is_granted('ROLE_USER') %}
    {% include 'quack/_form.html.twig' with {'placeholder':'Répondre à @' ~ quack.user.duckname} %}
  {% endif %}

{% endblock %}